- name: Install Python 2
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: Update Package List
  apt: update_cache=yes cache_valid_time=3600

- name: Install Modules
  apt: name={{ item }} state=present
  with_items:
    - vim
    - git
